### PR TITLE
Update gltf2 + draco extension loader.

### PR DESCRIPTION
**Pull request by fanzhanggoogle**
Hi Don,
I've updated the branch. Mostly merge with dev and some minor fixes. I've been using this branch to test other gltf exporter with draco extension (e.g. gltf-pipeline, collada2gltf). Let me know how you want to proceed. We hope to get it ready so we could merge to main 3JS repo when the draco extension spec is settled. Thanks. 

@donmccurdy

### CODE REVIEW

**Comment by donmccurdy** [comment]
Thanks! I went ahead and merged this, but do have a couple concerns:

1. It appears that `isVersionSupported(version, callback)` is never invoking the callback. Is this a known issue?
2. I'm nervous about the way we're using a callback and trusting that it will actually be invoked synchronously. I will refactor `loadMeshes` so that things would not fail if the callback were really asynchronous.

**Comment by donmccurdy** [comment]
I cleaned up (2) above, so that the geometries can be loaded asynchronously. 

See: https://github.com/mrdoob/three.js/compare/dev...donmccurdy:feat-gltf-draco-extension?diff=split

**Comment by fanzhanggoogle** [comment]
Sorry for the late reply. Thanks for mention that. Since we are in the middle of a new bitstream release, I'll fix that once we settled on the release.

**Comment by donmccurdy** [comment]
Great! Do you expect that would be days, weeks, or...? Should I try to merge this to three.js in the meantime, or wait until the bitstream update?

**Comment by fanzhanggoogle** [comment]
@donmccurdy  I have a fix for the isVersionSupported, but currently waiting for the Webassembly pull request to be merged [PR](https://github.com/mrdoob/three.js/pull/11391). Meanwhile, we plan to release the 1.0 in the coming weeks. Most of the work is ready, just need to refine some API.

**Pull request merged**
